<?php

namespace App\ProjectBundle\Entity;

/**
 * DeliveryServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
