<?php

namespace App\ProjectBundle\Entity;

/**
 * ProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProducers()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p FROM AppProjectBundle:Producer p");
    }
}
