<?php

namespace App\ProjectBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProfile()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p FROM AppProjectBundle:User p");
    }
}
