services:
#    app_project.example:
#        class: App\ProjectBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#    app_project.admin.author:
#        class: App\ProjectBundle\Admin\AuthorAdmin
#        arguments: [~, App\ProjectBundle\Entity\Author, AppProjectBundle:AuthorAdmin]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: Author}

#    app_project.admin.author:
#        class: App\ProjectBundle\Admin\AuthorAdmin
#        arguments: [~, App\ProjectBundle\Entity\Author, SonataAdminBundle:CRUD]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: Author}
    app_project.admin.product:
        class: App\ProjectBundle\Admin\ProductAdmin
        arguments: [~, App\ProjectBundle\Entity\Product, AppProjectBundle:ProductAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product}

    app_project.admin.product_category:
        class: App\ProjectBundle\Admin\ProductCategoryAdmin
        arguments: [~, App\ProjectBundle\Entity\ProductCategory, AppProjectBundle:ProductCategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProductCategory}

    app_project.admin.producer:
        class: App\ProjectBundle\Admin\ProducerAdmin
        arguments: [~, App\ProjectBundle\Entity\Producer, AppProjectBundle:ProducerAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Producer}

    weather.service:
            class: App\ProjectBundle\Services\WeatherService
            arguments: []